### ISSUE TITLE
Pin Buster

### ISSUE THREAD

**Issue by marvhus** [SSGorg/Cryptex#11]
Remember to check off in #1 when done

(Idk why we originally made this in the old version of Cryptex, but why not add it to the new version of cryptex)

**Comment by marvhus** [comment]
https://github.com/SSGorg/Cryptex-old/blob/master/ciphers/pb.py

**Comment by mastdev** [comment]
Hi, I would like to try my hands on this issue. Please assign it to me.

**Comment by mastdev** [comment]
Hi @ItsJustShepherd, Yes I am working on it and push the changes soon.

**Comment by marvhus** [comment]
Closing since this was merged in #60
