### ISSUE TITLE
Create CODE_OF_CONDUCT.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by marvhus** [SSGorg/Cryptex#13]
TODO:
- [x] CONTRIBUTING.md
- [x] CODE_OF_CONDUCT.md

**Comment by kuberaspeaking** [comment]
Hi, can you assign this to me?

**Comment by amitkumar-y** [comment]
Hi @marvhus , can you assign this to me to ad CODE_OF_CONDUCT.md ?
