### ISSUE TITLE
Playfair Cipher

### ISSUE THREAD

**Issue by marvhus** [SSGorg/Cryptex#15]
https://en.wikipedia.org/wiki/Playfair_cipher

**Comment by ashiskumarnaik** [comment]
Hi @marvhus any more details on what to do in this issue ?

**Comment by marvhus** [comment]
> Hi @marvhus any more details on what to do in this issue ?

Add an encrypt, and decrypt method.
Also if you want you can try to add something to brute force the decryption.

Also, it would be nice to change what characters is not in the 5x5 matrix, 
which normally is J (see the linked Wikipedia page for more info on that)

**Comment by marvhus** [comment]
Do you want me to assign you to this issue?

**Comment by ashiskumarnaik** [comment]
Yeah I would love to do it. Assign me.

**Comment by marvhus** [comment]
#1

**Comment by mastdev** [comment]
Hi @marvhus . As there hasn't been any activity on this issue for a while, I would like to resolve this issue. Kindly review the PR #67 with Playfair Cipher.
Feel free to add any suggestion. Thanks.

**Comment by mastdev** [comment]
Thanks @marvhus. 😃 Felt great to contribute.
