### ISSUE TITLE
Cryptex install / update script

### ISSUE THREAD

**Issue by AlexKollar** [SSGorg/Cryptex#17]
So we want to set it up that Cryptex can actually be installed to the machine post git clone. 

Ideally this will be in a .Cryptex folder in the users home directory.

Right now we are focusing on Linux installation but ideally eventually we will rack it up for windows and mac as well

Bonus points for being able to use an update command as the repo changes at the install point as well.

**Comment by ashiskumarnaik** [comment]
Hi @AlexKollar Can u assign it to me ? I would like to work on it.

**Comment by AlexKollar** [comment]
Got you!

**Comment by AlexKollar** [comment]
My bad, I am still learning how to work git. I still Do a lot of my work through VS Code even though I am slowly working my way towards pure command line. Using NVIM and Git commands. 

Which reminds me I should set that up.

**Comment by AlexKollar** [comment]
I'm going to close this one off for now. I think maybe we should the updater as time goes on. 90% of people using Cryptex right now are using it for development reasons so for us its as simple as a git pull in the repo folder and re-running the installer.
