### ISSUE TITLE
Add MonoAlphabetic Cipher

### ISSUE THREAD

**Issue by Ramisky** [SSGorg/Cryptex#20]
https://www.101computing.net/mono-alphabetic-substitution-cipher/

**Comment by marvhus** [comment]
Thanks for the suggestion.
I added it to The checklist at #1 
Do you want me to assign you to this issue?

**Comment by Ramisky** [comment]
> Thanks for the suggestion. I added it to The checklist at #1 Do you want me to assign you to this issue?

please do, I already finished the implementation!

**Comment by marvhus** [comment]
#21
