### ISSUE TITLE
Add Bacon's Chiper (Baconian Chiper)

### ISSUE THREAD

**Issue by Iqrar99** [SSGorg/Cryptex#24]
New chiper proposal to be added: Bacon's chiper (https://en.wikipedia.org/wiki/Bacon%27s_cipher)

**Comment by AlexKollar** [comment]
@marvhus - it has bacon in the name... 
We need to do this... Its a moral imperative.

**Comment by marvhus** [comment]
@AlexKollar we must

**Comment by AlexKollar** [comment]
I Have given this a priority of X-Large with an urgent tag. 
Hopefully people come in here and read this for context. 🤣

**Comment by Iqrar99** [comment]
If it's okay, I can work on this since I already understand the concept of this chiper.

**Comment by Iqrar99** [comment]
I have implemented the chiper in #33, feel free to check and review.
