### ISSUE TITLE
Install.sh bugged out on Debian + Deb variant

### ISSUE THREAD

**Issue by AlexKollar** [SSGorg/Cryptex#27]
I tried to install cryptex on Wallalabs earlier and it threw an error I need to fix later tonight. I wanted to put this here just to remind myself.

**Comment by AlexKollar** [comment]
Will do I know it was a fat finger on the path.

**Comment by marvhus** [comment]
@AlexKollar 
Has the status on this changed after the change from a shell/bash script to a python script?

**Comment by marvhus** [comment]
maybe I'll spin up some vm's later and test it
