### ISSUE TITLE
implementation of affine cipher

### ISSUE THREAD

**Issue by ShyamSunder149** [SSGorg/Cryptex#35]
I can do implementation of affine cipher using python... Can U assign this issue to me ??

**Comment by marvhus** [comment]
#1

**Comment by mastdev** [comment]
Hi @ShyamSunder149, are you still working on the issue? I would also like to be involved. Let me know if I can help.

**Comment by mastdev** [comment]
Hi @marvhus. With Hacktoberfest closing soon, and unfortunately not receiving any update from @ShyamSunder149. 
I have taken the initiative to implement Affine Cipher. 
Request you to please review the PR. Thanks.
