### ISSUE TITLE
Autokey Cipher

### ISSUE THREAD

**Issue by nga1hte** [SSGorg/Cryptex#40]
Hello, I would like to add autokey cipher to the list of ciphers. I believe that it is an important cipher to have since it is more secure than vignere cipher since vignere has limited key. Can you assign this to me? https://en.wikipedia.org/wiki/Autokey_cipher

**Comment by AlexKollar** [comment]
Fair deal! Also if you are interested in continued work with us post hacktoberfest we would love to have you around!

**Comment by nga1hte** [comment]
encoding that deals with excluded characters in both text and key
![Screenshot from 2022-10-15 10-31-48](https://user-images.githubusercontent.com/60479593/195969831-48e4666b-c013-4495-bbc6-566e970f41f8.png)
decoding 
![Screenshot from 2022-10-15 10-31-59](https://user-images.githubusercontent.com/60479593/195969847-567ed71c-8b86-4801-bbbd-7bc946f7c36f.png)
