### ISSUE TITLE
Enhancement of Readme file 

### ISSUE THREAD

**Issue by payallenka** [SSGorg/Cryptex#48]
I would like to contribute to your project by adding the Screenshot of the output - that is displayed when the code is run on VSCode.
I wish to participate in hacktoberfest. It will be great if you allow to add hacktoberfest to this issue.

**Comment by AlexKollar** [comment]
@marvhus and I were just talking about fixing up the README a bit. 
What all did you have in mind? Since we are leaning toward simplifying it as most of the instructional stuff exists in the wiki now.

**Comment by payallenka** [comment]
I'll run the code on VSCode and add the Screen shots of it under the heading "Output of Code as on VSCode"
If you agree then please assign the issue to me.

**Comment by marvhus** [comment]
btw I did some [changes](https://github.com/SSGorg/Cryptex/commit/53128a97235db39c304ef996b235f108ce08f592) to the README.md in the [beta branch](https://github.com/SSGorg/Cryptex/tree/beta).
Also the pr #55 added some stuff to the README.md in the [beta branch](https://github.com/SSGorg/Cryptex/tree/beta).

So try to avoid causing merge conficts with your changes.

**Comment by marvhus** [comment]
this seams inactive/fixed so I'll close it.

Reopen it if you feel like it isn't complete, etc.

**Comment by payallenka** [comment]
Ok
