### ISSUE TITLE
Add the ability to download / install beta branch to the installer. 

### ISSUE THREAD

**Issue by AlexKollar** [SSGorg/Cryptex#63]
This one kinda speaks for itself. 
Only when it installs beta we should allow for the use of 'cryptexbeta' for the system alias.

This would allow us to make further use of the update function as well 😉

**Comment by marvhus** [comment]
Note: if you use git worktree, you can get the beta branch using
```bash
git clone https://github.com/SSGorg/Cryptex.git --bare Cryptex
cd Cryptex
git worktree add beta
cd beta
git pull
```

**Comment by AlexKollar** [comment]
I suppose I could add this to the wiki documentation. I just figured having it all in the installer would make it easy for some people but I also suppose it goes against github workflow. 

Personal Checklist:
- [ ] Linux Better
- [ ] Properly learn the neuances of github 

😁

**Comment by marvhus** [comment]
> I suppose I could add this to the wiki documentation. I just figured having it all in the installer would make it easy for some people but I also suppose it goes against github workflow.
> 
> Personal Checklist:
> 
>     * [ ]  Linux Better
> 
>     * [ ]  Properly learn the neuances of github
> 
> 
> grin

I could try to add something to do a thing with the installer

**Comment by marvhus** [comment]
as of the release of 1.0.0 I have decided we'll stop using the beta branch, and rather rely on tags in github.
So I'll close this.
