### ISSUE TITLE
won't install on windows 10 pro with cygwin64

### ISSUE THREAD

**Issue by digitalsilicon** [SSGorg/Cryptex#64]
![bugcryptex](https://user-images.githubusercontent.com/7418187/198195594-b918df4c-dff1-4819-b4c7-996d7dfbb326.png)

**Comment by marvhus** [comment]
try doing `python3 -m pip install requests`

**Comment by 1T57H3F0X** [comment]
@digitalsilicon are you still having this issue?

**Comment by marvhus** [comment]
use wsl

**Comment by digitalsilicon** [comment]
> use wsl

Tested in Kali Linux and Debian in WSL for Windows 10 Pro, can confirm that it works in those distros on Windows Subsystem for Linux. 👍  Forget using Cygwin in Win 10 Pro, WSL++
