### ISSUE TITLE
Cryptex Translate function is broken

### ISSUE THREAD

**Issue by AlexKollar** [SSGorg/Cryptex#65]
![image](https://user-images.githubusercontent.com/89718570/198516385-53889cae-47b7-4ebc-b886-dda711ea3e44.png)

**Comment by marvhus** [comment]
If this is what I think it is,
then I fixed this in the beta branch.
So either wait for the 1.0.0 merge in a few days, download the requirements.txt and install the correct bersion of the package, or switch over to the beta branch.

**Comment by AlexKollar** [comment]
This was on beta branch. 😉

**Comment by marvhus** [comment]
> This was on beta branch. 😉

Ah ok, then run `python3 -m pip install -r requirements.txt` in the root of the beta branch

**Comment by AlexKollar** [comment]
Yeah, still popping errors after:

- git pull
- requirements install
- reinstall of cryptex.

Its odd. Might have something to do with the controller code.

**Comment by marvhus** [comment]
Have you checked the list of languages supported by using the `-lang` flag?
and checked if the one you entered is correct?

**Comment by AlexKollar** [comment]
@marvhus,
I did a straight copy paste between the example code (Modified to run with cryptex installed and aliased) on beta branch and I got this error. 

![image](https://user-images.githubusercontent.com/89718570/198913458-b7b5800c-c1f3-45f8-b313-9bbde106839c.png)

As far as I can tell this is the only existing error still in the code.

**Comment by marvhus** [comment]
> @marvhus,
> I did a straight copy paste between the example code (Modified to run with cryptex installed and aliased) on beta branch and I got this error. 
> 
> ![image](https://user-images.githubusercontent.com/89718570/198913458-b7b5800c-c1f3-45f8-b313-9bbde106839c.png)
> 
> As far as I can tell this is the only existing error still in the code.

are you doing this on the beta branch with the updated google translate package?

**Comment by AlexKollar** [comment]
I did a full re-install of Cryptex as a means of testing the installer for release.
Let me go back and see about updating translate. I kinda figured it would pull the latest when I did the install but I could be wrong.

**Comment by AlexKollar** [comment]
Yeah no, after doing an update to translate (Which said it was current) no change in error.

**Comment by marvhus** [comment]
@AlexKollar run this command:
```
python3 -m pip show translate
```

**Comment by AlexKollar** [comment]
> @AlexKollar run this command:
> 
> ```
> python3 -m pip show translate
> ```

![image](https://user-images.githubusercontent.com/89718570/198944701-8784c83e-b209-4ddc-bf20-45b99b83708b.png)

**Comment by marvhus** [comment]
@AlexKollar 
run this command
```
python3 -m pip install googletrans==3.1.0a0
```
then try using the cipher again

**Comment by AlexKollar** [comment]
![image](https://user-images.githubusercontent.com/89718570/198945676-6bafc54e-34a1-49a7-8644-1593647b07e1.png)


Ayeeeee, it works!

**Comment by marvhus** [comment]
This is an issue that was fixed in the test branch, but hasnt been merged yet
