### ISSUE TITLE
Issue with google translate not allowing cryptex to load

### ISSUE THREAD

**Issue by AlexKollar** [SSGorg/Cryptex#76]
Issue was presented to me by Elrich in the SSG Discord.   

![image](https://user-images.githubusercontent.com/89718570/232262329-5e8f1960-a1cf-44e4-8f7a-467f518c57b1.png)  
  
**Potential remedies I tried:**  

- Updated google translate library through pip
- Removed the == <version number> from translate package in requirements.txt
- Also added httpcore to requirements.txt  
  
Odds are I am over complicating this @marvhus opinion?

**Comment by marvhus** [comment]
I added the == to the translate package in requirements.txt on purpose... it breaks if it is the wrong version

**Comment by marvhus** [comment]
potential solution https://stackoverflow.com/questions/72796594/attributeerror-module-httpcore-has-no-attribute-synchttptransport

**Comment by marvhus** [comment]
changing the version to 4.0.0-rc1 seams to fix it

**Comment by marvhus** [comment]
I have a fix in https://github.com/SSGorg/Cryptex/tree/bug/google-translate I'll make a pr
